version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    #command: http-server dist
    ports:
      - "8100:3000"
    # volumes:
    #   - .:/app
    # working_dir: /app

